### ISSUE TITLE
イシューってどうやって使うんでしょう・・・

### ISSUE THREAD

**Issue by hacca** [mamimu-tetau/gulp#1]
イシューってどうやって使うんでしょうイシューってどうやって使うんでしょうイシューってどうやって使うんでしょうイシューってどうやって使うんでしょう @naconaconaco

**Comment by hacca** [comment]
ここにリプライ？

**Comment by naconaconaco** [comment]
ここ、テストアップ確認とかで使いました

**Comment by naconaconaco** [comment]
です、ここでリプライ。


- [x] mv崩れてる
- [x] mv崩れてる
- [ ] mv崩れてる
- [ ] mv崩れてる
- [ ] mv崩れてる

**Comment by naconaconaco** [comment]
こんなチェックリストで修正点把握もできます

**Comment by naconaconaco** [comment]
![image](https://user-images.githubusercontent.com/30341855/32258834-33441fde-bf00-11e7-9a09-9f8df402619e.png)

**Comment by naconaconaco** [comment]
画像のコピペできます。↑isuueの使い方サンプルです
